"""audit log enrichment

Revision ID: 4f2747671a6f
Revises: db318e221391
Create Date: 2026-08-19 13:16:20.776572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2747671a6f'
down_revision: Union[str, None] = 'db318e221391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('before', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('after', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'after')
    op.drop_column('audit_logs', 'before')
    op.drop_column('audit_logs', 'actor_role')
    # ### end Alembic commands ###
