"""initial schema

Revision ID: db318e221391
Revises: 
Create Date: 2026-08-19 12:21:35.770520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db318e221391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('modalities', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('head', sa.String(), nullable=True),
    sa.Column('staff', sa.Integer(), nullable=True),
    sa.Column('active_cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('doctors', sa.Integer(), nullable=True),
    sa.Column('patients', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_code_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('doctor', sa.Boolean(), nullable=True),
    sa.Column('patient', sa.Boolean(), nullable=True),
    sa.Column('technician', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('started', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('audience_role', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('tumor_size_mm', sa.Float(), nullable=True),
    sa.Column('er_status', sa.String(), nullable=True),
    sa.Column('pr_status', sa.String(), nullable=True),
    sa.Column('her2_status', sa.String(), nullable=True),
    sa.Column('ki67', sa.Float(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('nodes_involved', sa.Integer(), nullable=True),
    sa.Column('current_treatment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('survival_probability', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('diagnosed_on', sa.String(), nullable=True),
    sa.Column('twin_status', sa.String(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('comorbidities', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('previous_treatments', sa.JSON(), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('smoking_status', sa.String(), nullable=True),
    sa.Column('alcohol_use', sa.String(), nullable=True),
    sa.Column('surgical_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('doctor', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imaging_studies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('radiologist', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('panel', sa.String(), nullable=True),
    sa.Column('marker', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_report_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('twin_version', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('survival', sa.Float(), nullable=True),
    sa.Column('recurrence', sa.Float(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('twin_version', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('selected', sa.String(), nullable=True),
    sa.Column('compared', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survival', sa.Float(), nullable=True),
    sa.Column('response', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scenarios', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('regimen', sa.String(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('total_cycles', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.String(), nullable=True),
    sa.Column('next_dose', sa.String(), nullable=True),
    sa.Column('adherence', sa.Float(), nullable=True),
    sa.Column('side_effects', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('twin_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('taken_at', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twin_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tumor_size_mm', sa.Float(), nullable=True),
    sa.Column('survival', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('by', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_versions')
    op.drop_table('ocr_fields')
    op.drop_table('download_records')
    op.drop_table('document_versions')
    op.drop_table('twin_versions')
    op.drop_table('twin_snapshots')
    op.drop_table('treatment_plans')
    op.drop_table('timeline_events')
    op.drop_table('simulation_runs')
    op.drop_table('reports')
    op.drop_table('prediction_runs')
    op.drop_table('patient_report_refs')
    op.drop_table('lab_results')
    op.drop_table('imaging_studies')
    op.drop_table('documents')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('training_runs')
    op.drop_table('permissions')
    op.drop_table('performance_points')
    op.drop_table('patient_code_counters')
    op.drop_table('model_versions')
    op.drop_table('ml_models')
    op.drop_table('hospitals')
    op.drop_table('departments')
    op.drop_table('datasets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
