/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellDigitalTwinsRouteImport } from './routes/_shell.digital-twins'
import { Route as ShellExplainabilityRouteImport } from './routes/_shell.explainability'
import { Route as ShellPredictionsRouteImport } from './routes/_shell.predictions'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSimulatorRouteImport } from './routes/_shell.simulator'
import { Route as ShellPatientsIndexRouteImport } from './routes/_shell.patients.index'
import { Route as ShellPatientsPatientIdRouteImport } from './routes/_shell.patients.$patientId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDigitalTwinsRoute = ShellDigitalTwinsRouteImport.update({
  id: '/digital-twins',
  path: '/digital-twins',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExplainabilityRoute = ShellExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPredictionsRoute = ShellPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSimulatorRoute = ShellSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsIndexRoute = ShellPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsPatientIdRoute = ShellPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/digital-twins': typeof ShellDigitalTwinsRoute
  '/explainability': typeof ShellExplainabilityRoute
  '/predictions': typeof ShellPredictionsRoute
  '/reports': typeof ShellReportsRoute
  '/simulator': typeof ShellSimulatorRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/patients/': typeof ShellPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof ShellAnalyticsRoute
  '/digital-twins': typeof ShellDigitalTwinsRoute
  '/explainability': typeof ShellExplainabilityRoute
  '/predictions': typeof ShellPredictionsRoute
  '/reports': typeof ShellReportsRoute
  '/simulator': typeof ShellSimulatorRoute
  '/': typeof ShellIndexRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/patients': typeof ShellPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/digital-twins': typeof ShellDigitalTwinsRoute
  '/_shell/explainability': typeof ShellExplainabilityRoute
  '/_shell/predictions': typeof ShellPredictionsRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/simulator': typeof ShellSimulatorRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/_shell/patients/': typeof ShellPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/digital-twins'
    | '/explainability'
    | '/predictions'
    | '/reports'
    | '/simulator'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/digital-twins'
    | '/explainability'
    | '/predictions'
    | '/reports'
    | '/simulator'
    | '/'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/digital-twins'
    | '/_shell/explainability'
    | '/_shell/predictions'
    | '/_shell/reports'
    | '/_shell/simulator'
    | '/_shell/'
    | '/_shell/patients/$patientId'
    | '/_shell/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/digital-twins': {
      id: '/_shell/digital-twins'
      path: '/digital-twins'
      fullPath: '/digital-twins'
      preLoaderRoute: typeof ShellDigitalTwinsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/explainability': {
      id: '/_shell/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ShellExplainabilityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/predictions': {
      id: '/_shell/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof ShellPredictionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/simulator': {
      id: '/_shell/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof ShellSimulatorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients/': {
      id: '/_shell/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof ShellPatientsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients/$patientId': {
      id: '/_shell/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof ShellPatientsPatientIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDigitalTwinsRoute: typeof ShellDigitalTwinsRoute
  ShellExplainabilityRoute: typeof ShellExplainabilityRoute
  ShellPredictionsRoute: typeof ShellPredictionsRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSimulatorRoute: typeof ShellSimulatorRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellPatientsPatientIdRoute: typeof ShellPatientsPatientIdRoute
  ShellPatientsIndexRoute: typeof ShellPatientsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDigitalTwinsRoute: ShellDigitalTwinsRoute,
  ShellExplainabilityRoute: ShellExplainabilityRoute,
  ShellPredictionsRoute: ShellPredictionsRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSimulatorRoute: ShellSimulatorRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellPatientsPatientIdRoute: ShellPatientsPatientIdRoute,
  ShellPatientsIndexRoute: ShellPatientsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
