/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellPatientsIndexRouteImport } from './routes/_shell.patients.index'
import { Route as ShellPatientsPatientIdRouteImport } from './routes/_shell.patients.$patientId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsIndexRoute = ShellPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsPatientIdRoute = ShellPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/patients/': typeof ShellPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/patients': typeof ShellPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/patients/$patientId': typeof ShellPatientsPatientIdRoute
  '/_shell/patients/': typeof ShellPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patients/$patientId' | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patients/$patientId' | '/patients'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/patients/$patientId'
    | '/_shell/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients/': {
      id: '/_shell/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof ShellPatientsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients/$patientId': {
      id: '/_shell/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof ShellPatientsPatientIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellPatientsPatientIdRoute: typeof ShellPatientsPatientIdRoute
  ShellPatientsIndexRoute: typeof ShellPatientsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellPatientsPatientIdRoute: ShellPatientsPatientIdRoute,
  ShellPatientsIndexRoute: ShellPatientsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
